version: 2

builds:
  - id: proxy
    dir: proxy
    main: ./cmd
    binary: mcpx-proxy
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w"]

  - id: exec
    dir: servers/exec
    main: ./cmd
    binary: mcpx-exec
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w"]

  - id: debug
    dir: servers/debug
    main: ./cmd
    binary: mcpx-debug
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w"]

archives:
  - id: bundle
    builds: [proxy, exec, debug]
    name_template: "mcpx_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: proxy/gateway.yaml
        dst: gateway.yaml
      - src: commands/mcpx/**
        dst: commands/mcpx/
        strip_parent: true

checksum:
  name_template: "mcpx_{{ .Version }}_checksums.txt"

release:
  github:
    owner: nqhuy44
    name: mcpx
  name_template: "v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
